name: Azure Functions

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - run: yarn install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4

      - run: yarn nx affected -t build
      - run: yarn nx publish hello-func

      - name: Create deployment package
        run: |
          cd dist/apps/hello-func/net8.0/publish
          zip -r packages.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-func
          path: packages.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: hello-func
          path: .

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Function App
        id: fa
        uses: azure/functions-action@v1
        with:
          app-name: 'az204-compute-function-app-func'
          slot-name: 'production'
          package: .

      - name: Delete artifact
        uses: geekyeggo/delete-artifact@v5
        with:
          name: hello-func
